name: Docker Image CI

on: 
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: artis3n/docker-arch-ansible

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          ignore: DL3013,DL3007

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Export
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test the Docker image
        run: |
          docker run --name test-container -d --rm --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro ${{ env.IMAGE_NAME }}:test
          docker exec --tty test-container env TERM=xterm ansible --version
